### PR TITLE
Add Badges

### PR DESCRIPTION
**Pull request by chessbyte**

### CODE REVIEW

**Comment by NickLaMuro** [comment]
@chessbyte @Fryguy Hey, I totally missed this when it came in, but I am all good with this.

That said, are some of these services already turned on?  I noticed that travis is turned on when wrote up [this](https://github.com/ManageIQ/manageiq-performance/issues/7) when merging in a few PRs from Libor.

I assume that one of you has activated travis then and it doesn't require that a `.travis.yml` is present?

Are other services listed here activated or are we waiting something?

**Comment by Fryguy** [comment]
I'll have to take a look

**Comment by NickLaMuro** [comment]
As an FYI, I merged this a few days back to get the test suite passing:  https://github.com/ManageIQ/manageiq-performance/pull/9

And have been using that as a barrier lately before merging anything else.  Let me know if you decide to activate anything other services so I can get things working for that as well.

**Comment by kbrock** [comment]
cool. Can Haz more badges?
... or we don't need no stinkin' badges?

**Comment by NickLaMuro** [comment]
Closing this in favor of https://github.com/ManageIQ/manageiq-performance/pull/46 and some follow up PRs.

**Pull request closed without merging**
