### PR TITLE
Optionally add stackprof to the installation script generation

### PR DESCRIPTION
**Pull request by NickLaMuro**
Purpose
-------
On some systems, it will be requested to do extra profiling to the appliance, and this allows the installation script to include and install stackprof onto the appliance to be used with `manageiq-performance`.

Implementation
--------------
A few things were added to make this work

**`GemBase64::find_gemspec_for`:**  This method will find the latest spec for a given gem, either one that exists, or downloading one that is already available on the system.  Being that stackprof is an optional dependency for this project, it may or may not exist on the developers machine at the time of generation (even though it is currently a development dependency, it is possible that might change in the future, or this script is run without bundling).

**`GemBase64::gem_as_base64_string` and `GemBase64::gem_as_tar_io` updates:**  These two methods now take optional arguments to pass in either their own gemfile contents or gemspec respectively.  This allows the contents from them to be reused for stackprof.

**Updates to the template:**  The template now has multiple conditionals in it around adding stackprof content.  This is activated when the `@stackprof_gemspec` and `@stackprof_gem_base64_string` instance variables are present when rendering the template.  These are added by the new task...

**Added new task `include_stackprof`:**  This task is in charge of adding the instance variables `@stackprof_gemspec` and `@stackprof_gem_base64_string` so the template can make use of it.  Makes use of the new features in `GemBase64`.

TODO
----
* [x] Clean up test output

QA
--
* Generate a script using `$ rake include_stackprof generate_install_script`
* Run that script on an appliance, and confirm that it works, and the server can be restarted
* Hit a few routes and confirm that stackprof data is generated along with the other middleware plugins

### CODE REVIEW

**Comment by kbrock** [comment]
Looks good.
Disclaimer: I did not run it

I digress: This installation script sure looks like it would be a great separate tool.

```
generate_installer.sh directory/ gem_name
```

**Comment by NickLaMuro** [comment]
@kbrock Actually testing on an appliance as we speak, and unfortunately there is a snag (which I was somewhat expecting):  We don't have the `ruby.h` files so the native extensions can install.  I think getting around this will be a little tricker, which does stink...

That said, #25 seems to work just as expected when installing something like `vcr`, so there is that.

> I digress: This installation script sure looks like it would be a great separate tool.

Yeah, this was originally for the needs of this gem, but I can definitely see it being used more universally in MIQ.

**Comment by NickLaMuro** [comment]
Note for myself when I get back to this:  setup a docker-container for building c-extensions so we can pre-compile gems and ship them directly.  Would require some changes to the script when doing this though...

**Comment by kbrock** [comment]
docker FTW!

**Comment by kbrock** [comment]
:shipit: slick (and requires at least 1 PhD)

**Pull request merged**
