### PR TITLE
Return response header

### PR DESCRIPTION
**Pull request by kbrock**
Would like a way to automate the caller being able to view the resulting data.

First step is to return the id for the sample.

Not thrilled with the sprawl. Advice please

### CODE REVIEW

**Comment by NickLaMuro** [comment]
So where do you see this being used (use case wise)?

Guessing here, but I assume this would be something akin to `rack-mini-profiler` showing the data in a JS widget on the page (makes a separate request to do so, but possibly this is for something else.  If it is the above, would injecting this into the html inline at the bottom of the page be easier then pushing this into the view to make a separate request?  I honestly don't know, just a thought.

I have some changes in the pipeline that I haven't pushed yet (sorry 😞 ) that are touching this class, so I am going to say give me a bit before we go further with this and can discuss after that.

**Comment by kbrock** [comment]
Maybe not a browser use case, but the curl use case. so the ids are brought back, and they are used by the caller to format a table

**Comment by NickLaMuro** [comment]
So if it is a command line use case, then I guess I don't understand since it technically exists already (as far as I can tell, thought it probably isn't clear).

So the `lib/miq_performance/requestor.rb` is used by the `miq_performance:benchmark` rake task, and in it the [HTTP Header is set](https://github.com/NickLaMuro/miq_performance/blob/master/lib/miq_performance/requestor.rb#L86) for each request and makes it uniq for each one (down to less than a millisecond, which is way faster than our app will be able to process a request anyway, though, could probably be improved further to prevent collision).

Point being though, is the caller initiating the request has already had the control to define the ID, so I don't see how manipulating it here is providing any further improvement to that.

**Comment by kbrock** [comment]
@NickLaMuro ok. I didn't read that. thanks.

I'm used to a different workflow.

Thought the server would set the id and send to the client. Then the client could later call the server with the id and download the data

**Comment by kbrock** [comment]
we can do something like this later

**Pull request closed without merging**
